name: Noetic

on: pull_request

jobs:
    job1:
        name: Build
        runs-on: ubuntu-20.04
        container: ros:noetic
        steps:
            - name: Install Git
              run: |
                  apt-get update
                  apt-get install -y git
              shell: bash
            - name: Clone repository
              run: |
                  mkdir -p ~/catkin_ws/src
                  cd ~/catkin_ws/src
                  git clone https://github.com/rsasaki0109/laser_deskew
            - name: Install dependencies
              run: |
                  source /opt/ros/noetic/setup.bash
                  cd ~/catkin_ws/src
                  rosdep update
                  rosdep install -r -y --from-paths . --ignore-src
                  apt-get install -y ros-noetic-tf
                  apt-get install -y ros-noetic-pcl-ros
              shell: bash
            - name: Install build tools
              run: |
                  apt-get install -y build-essential
            - name: Build packages
              run: |
                  source /opt/ros/noetic/setup.bash
                  cd ~/catkin_ws
                  catkin_make -j4
                  source ~/catkin_ws/devel/setup.bash
              shell: bash
